services:
  react-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./node_modules
        target: /app/node_modules
    environment:
      - HOST=0.0.0.0
    container_name: react-dev
